### ISSUE TITLE
stamp_changelog not adding tags correctly

### ISSUE THREAD

**Issue by simonbs** [pajapro/fastlane-plugin-changelog#11]
When using `stamp_changelog` with a Git tag, the tag does not seem to be appended correctly.

Stamping the following change log with `stamp_changelog(section_identifier: "1.0 (27)", git_tag: "example")` results in the change log in the bottom of this post.

```
# Change Log
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/) and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased]
- Testing

## [1.0 (26)] - 2016-10-31
- Adds build for feature/demo branch. Testing fastlane setup.

## [1.0 (25)] - 2016-10-31
- Tests distribution using fastlane.

## [1.0 (24)] - 2016-10-30
- Tests distribution of builds with fastlane.

## [1.0 (21)] - 2016-10-30
- Attempts automating build process.
```

Below is the result of stamping the above change log with a section identifier of "1.0 (27)" and a Git tag of "example".

```
# Change Log
All notable changes to this project will be documented in this file.

The format is based on [Keep a Changelog](http://keepachangelog.com/) and this project adheres to [Semantic Versioning](http://semver.org/).

## [Unreleased]

## [1.0 (27)] - 2016-10-31
- Testing

## [1.0 (26)] - 2016-10-31
- Adds build for feature/demo branch. Testing fastlane setup.

## [1.0 (25)] - 2016-10-31
- Tests distribution using fastlane.

## [1.0 (24)] - 2016-10-30
- Tests distribution of builds with fastlane.

## [1.0 (21)] - 2016-10-30
- Attempts automating build process.
1.0 (27)example- Attempts automating build process.
```

**Comment by pajapro** [comment]
Hey @simonbs, thanks a lot for reporting this behaviour.

The only reason why `stamp_changelog` needs `git_tag` param is for creating a link to [compare tags on GitHub](https://help.github.com/articles/comparing-commits-across-time/). When you pass `git_tag` paramater to `stamp_changelog` action, the plugin _expects_ that you provided a link to your repo on GitHub. 

You can provide the link to your repo in 2 ways:

1. [fastlane-plugin-changelog](https://github.com/pajapro/fastlane-plugin-changelog) comes with an installation wizard. This wizard is launched automatically when you intend to use the plugin, but there is no `CHANGELOG.md` in your project root. Wizard generates a template `CHANGELOG.md` file. Moreover, it asks you if you want to create links for comparing tags on GitHub - that's where you want to type in repo URL. 
![screen shot 2016-11-06 at 18 05 37](https://cloud.githubusercontent.com/assets/3673765/20039850/1d850516-a44c-11e6-9017-1b5807b54019.png)

2. Just copy and paste the link to your project repo at the bottom of your `CHANGELOG.md` (see [example format](https://raw.githubusercontent.com/pajapro/pied-piper-app/master/CHANGELOG.md))

Another solution is that you simply do not provide `git_tag` param at all. This would result in correct stamping, but sections would not link to [compare tags on GitHub](https://help.github.com/articles/comparing-commits-across-time/). 

Let me know if it helped?

**Comment by pajapro** [comment]
@simonbs has this answer help you☝️ ?

**Comment by simonbs** [comment]
@pajapro Yes, sorry for the missing response. I did not provide a link to a Github repository as the project is located on Bitbucket. I might look into adding support for Bitbucket at some point.

We're using the changelog plugin on multiple projects and are very happy about it. Thank you.
