### ISSUE TITLE
Documentation error for read_changelog example

### ISSUE THREAD

**Issue by ferrerod** [pajapro/fastlane-plugin-changelog#21]
In the README example given, the excluded_markdown_elements shows double quotes within the brackets which causes the plugin to fail. If a list of elements is given, remove the single quotes on the outside of the brackets and use single quotes and commas to support the markdown elements to exclude.

BAD:
read_changelog(
  changelog_path: './custom_folder/CHANGELOG.md',	# Specify path to CHANGELOG.md
  section_identifier: '[Unreleased]',	# Specify what section to read
  excluded_markdown_elements: '["###"]'	# Specify which markdown elements should be excluded
)

GOOD:
read_changelog(
  changelog_path: './custom_folder/CHANGELOG.md',	# Specify path to CHANGELOG.md
  section_identifier: '[Unreleased]',	# Specify what section to read
  excluded_markdown_elements: ['###']	# Specify which markdown elements should be excluded
)

**Comment by pajapro** [comment]
Hey @ferrerod, thank you for reporting this issue and ensuring future users of this plugin won't be misled mistake in documentation. I have [fixed it](https://github.com/pajapro/fastlane-plugin-changelog#--read_changelog) now.
