### ISSUE TITLE
There is a way to changelog don't ask to create a changelog.md file??

### ISSUE THREAD

**Issue by ggoulart** [pajapro/fastlane-plugin-changelog#23]
Hi,

There is a way to changelog don't ask to create a changelog.md file?? I know that it will search for an existing file, but mine is in another directory.

Thank you.

**Comment by pajapro** [comment]
Hi @ggoulart 

not really - [it always looks for](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/lib/fastlane/plugin/changelog.rb#L23) `CHANGELOG.md` in the root of your project.

**Comment by kevin-wolf** [comment]
Hello @pajapro 

I think that if I'd specify the `changelog_path` setting it *should not* prompt for creating the CHANGELOG.md file.

## Why?

I am using React Native to develop my application, so I like to maintain a single `CHANGELOG.md` file for both platforms on the project root.

Is there any way to avoid this? The solution I found is creating an empty `CHANGELOG.md` file on my `android` and `ios` folder.

**Comment by ggoulart** [comment]
Hi @pajapro 

I have the same problem then you, working in a React Native project and I want a single `CHANGELOG.md`, the solution that I find was to have the `CHANGELOG.md` in the root of my project and create two symbolic links inside `android` and `ios` folders.

**Comment by JaEdmuva** [comment]
@kevin-wolf is right! If I specify the changelog_path I should not be prompted for creating a CHANGELOG.md file 
I'm not a Ruby developer, so I can not create a PR, not right now at least. Please help us out. TVM

**Comment by pajapro** [comment]
Hi @ggoulart, @kevinwolfcr and @JaEdmuva

thanks for reporting this issue and sorry for being radio silent! I have fixed it now (https://github.com/pajapro/fastlane-plugin-changelog/pull/35) and shipped in release [v0.10.0](https://github.com/pajapro/fastlane-plugin-changelog/releases/tag/v0.10.0)

You can now do e.g.: 
`fastlane run read_changelog changelog_path:'/Users/pavelprochazka/Desktop/CHANGELOG.md'` and you will _not_ be asked to create a new `CHANGELOG.md` in the default location. You should be able to remove your dummy file (temporary workaround) as well now 😉.

Hope it will fix your issues.
