### ISSUE TITLE
Plugin holding open files? Unable to delete windows workspace due to busy git pack file

### ISSUE THREAD

**Issue by VermaGa** [pajapro/fastlane-plugin-changelog#25]
I get the error Unable to delete windows workspace due to busy git pack file after I build and use the Git changelog plugin.

seems this was reported before as well against jenkins. 
https://issues.jenkins-ci.org/browse/JENKINS-19994

**Comment by pajapro** [comment]
Hey @VermaGa, this sounds like an error related to Jenkins running on Windows rather than error related to this plugin.
