### ISSUE TITLE
Asks to create changelog.md when specifying changelog_path

### ISSUE THREAD

**Issue by angularsen** [pajapro/fastlane-plugin-changelog#28]
I have my CHANGELOG.md file outside the project to share across iOS and Android.
When stamping it, it asks me to create the file in the default location because it can't find it:
`fastlane run stamp_changelog(changelog_path: '../../CHANGELOG.md', ....)`

As a workaround I've created a dummy file in that place, but it would be good to not have to.

**Comment by pajapro** [comment]
Hi @angularsen,

thanks for reporting this issue! I have fixed it now (https://github.com/pajapro/fastlane-plugin-changelog/pull/35) and shipped in release [v0.10.0](https://github.com/pajapro/fastlane-plugin-changelog/releases/tag/v0.10.0)

You can now do e.g.: 
`fastlane run read_changelog changelog_path:'/Users/pavelprochazka/Desktop/CHANGELOG.md'` and you will _not_ be asked to create a new `CHANGELOG.md` in the default location 😉. You should be able to remove your dummy file as well now.
