### ISSUE TITLE
Multilanguage changelog

### ISSUE THREAD

**Issue by Emailrus** [pajapro/fastlane-plugin-changelog#29]
Hi,

Is there any support for having localizable changelog? is there any other way than keeping multiple md files and iterating through them in custom lanes for read and stamp actions?

Thank you

**Comment by pajapro** [comment]
Hi @Emailrus,

No, multi-language is currently not supported. Neither support for multiple `CHANGELOG.md` files. Feel free to create  a PR.

Regards,
Pavel
