### ISSUE TITLE
Changelog.md from another git repo 

### ISSUE THREAD

**Issue by RishabhTayal** [pajapro/fastlane-plugin-changelog#30]
Is there a way to get the Changelog.md file from another git repo?

**Comment by pajapro** [comment]
Not at the moment - what's the use use case?

**Comment by RishabhTayal** [comment]
The idea is to have a separate repo for Changelog.md and it would clone that repo and use the Changelog from there. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by pajapro** [comment]
Can't you then run `fastlane-plugin-changelog` in that _separate_  repo?

**Comment by byteorb** [comment]
But then how would we get the change log text in the main repo?

**Comment by pajapro** [comment]
> Is there a way to get the Changelog.md file from another git repo?

How about just having a script to clone that _another_ repo and move `Changelog.md` to a folder from which you execute `fastlane`?
