### ISSUE TITLE
Changelogs not being updated to TestFlight

### ISSUE THREAD

**Issue by joelgetaction** [pajapro/fastlane-plugin-changelog#31]
See https://github.com/fastlane/fastlane/issues/13229 .

Not clear if it's an issue with Fastlane or changelog but I have not changed fastlane or changelog practices or my code for those locally and this just started breaking all of a sudden.  Any ideas?

Thanks! :-)

**Comment by pajapro** [comment]
Hey @joelgetaction ,

it's likely an issue with Fastlane itself not this plugin - it only manipulates content of your `CHANGELOG.md` not the actual upload to TestFlight 😉
