### ISSUE TITLE
Possibility to select latest section (independently of its name)

### ISSUE THREAD

**Issue by acecilia** [pajapro/fastlane-plugin-changelog#38]
Hi:

My changelog is sorted with the last changes on top. Would it be possible to select the last section without the need of specifying its identifier?

Thanks

**Comment by pajapro** [comment]
Hi @acecilia ,

> Would it be possible to select the last section without the need of specifying its identifier?

If your changelog is sorted as in https://keepachangelog.com/en/1.0.0/ than running [`read_changelog`](https://github.com/pajapro/fastlane-plugin-changelog#--read_changelog) action will by default read whatever is in the `[Unreleased]` section - does it make sense?

**Comment by acecilia** [comment]
Hi @pajapro,

At the moment I am doing that, but what I would like to do is:
1- Make a release branch.
2- Change `[ureleased]` to whatever I want, for example `[1.0.1 UAT1 / 1.0.3 UAT2]`.
3- Commit that changelog change.
4- Use fastlane for distribution using Fabric, and in the notes of fabric, add the content of the `[1.0.1 UAT1 / 1.0.3 UAT2]` section, which is the one on the top of the document. Note that the identifier can be any text, so I would like to be able to pick the last section without specifying any identifier.

I guess this is not possible at the moment. What do you think?

**Comment by pajapro** [comment]
Hi @acecilia, 

first of all sorry for late reply.

Second of all, this plugin does not support reading of _the last_ section in changelog regardless of its name. By default [read_changelog](https://github.com/pajapro/fastlane-plugin-changelog#--read_changelog) action, picks `[Unreleased]` section _or_ you can explicitly specify the section you want to read by using the [section_identifier](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/spec/read_changelog_action_spec.rb#L14-L21). Therefore, in your release branch you could for example use `read_changelog(section_identifier: [1.0.1 UAT1 / 1.0.3 UAT2])`.

Let me know whether it helped?

**Comment by acecilia** [comment]
In the end I am attaching the whole changelog, and not only the last section
