### ISSUE TITLE
update_changelog action: No way to disable append_date 

### ISSUE THREAD

**Issue by bpollman** [pajapro/fastlane-plugin-changelog#40]
Due to the way update_changelog params are setup there is no way to disable the date append feature. 

I have tried using `false`, `nil`, the ENV variable,etc.

Fail scenario:
`update_changelog append_date: false)`

**Comment by pajapro** [comment]
Hey @bpollman 

> Due to the way update_changelog params are setup there is no way to disable the date append feature.

That's correct, `update_changelog` does not support option to disable date. Let me turn this issue into a feature enhancement

**Comment by pajapro** [comment]
Hi @bpollman,

thanks for bringing this up! There truly was [an issue](https://github.com/pajapro/fastlane-plugin-changelog/pull/41/files#diff-441d39a090f1cf866dc61591a4380d41R121) with `append_date` param.
