### ISSUE TITLE
WARNING: No changes in [Unreleased] section to stamp!

### ISSUE THREAD

**Issue by zhuyuping** [pajapro/fastlane-plugin-changelog#45]
How can I generate the latest Unreleased Change Log?

here is the git commit log
![WX20191025-203651](https://user-images.githubusercontent.com/16640301/67571711-34bcee80-f767-11e9-9134-c1ee06e57dea.png)

here is Fastfile:
```
lane :getVersion do
    version_number = get_version_number(target: "XAGApp")
    build_number = get_build_number(xcodeproj: "XAGApp.xcodeproj")
    version_number + "(" + build_number + ")"
  end
  
  lane :test do
    version = getVersion
    stamp_changelog(section_identifier: "Build #{version}")
  end
```

here the change log after 'fastlane test'
![WX20191025-195349](https://user-images.githubusercontent.com/16640301/67569350-2f5ca580-f761-11e9-8474-5a4b65e4d922.png)

can you help me ? 
or Can this tool automatically generate change log files?
mannually write log in CHANGELOG.md file?

**Comment by pajapro** [comment]
Hi @zhuyuping,

As far as I understand you want to generate changelog from your git commits - correct? 
If so, I am afraid that [fastlane-plugin-changelog](https://github.com/pajapro/fastlane-plugin-changelog) won't help you. Pre-requisite for [fastlane-plugin-changelog](https://github.com/pajapro/fastlane-plugin-changelog) to work is that you manually write content of `CHANGELOG.md` see [README.md](https://github.com/pajapro/fastlane-plugin-changelog#about-changelog).

However, what may help you is [changelog_from_git_commits](https://docs.fastlane.tools/actions/changelog_from_git_commits/) or [make_changelog_from_jenkins](https://docs.fastlane.tools/actions/make_changelog_from_jenkins/)
