### ISSUE TITLE
Android Usage?

### ISSUE THREAD

**Issue by Psiiirus** [pajapro/fastlane-plugin-changelog#46]
Hi,
the iOS workflow looks quite straight forward to me but unf. O don't really get how I can integrate this into my android fastlane deployment to set up automated changelog texts per build

Thanks,
Toni

**Comment by edisonywh** [comment]
I am having trouble with this as well

**Comment by edisonywh** [comment]
@Psiiirus to give you an idea, I wrote up a little hackish version for myself, with reference to [this post here](https://blog.blueapron.io/release-notes-using-fastlane-fba80240dc4d):

```ruby
# android/fastlane

FileNotFound = Class.new(StandardError)

def fetch_version
  path = "../local.properties"

  if File.exists?(path)
    content = File.read(path)

    buildRegex = /(?<=flutter.versionCode=).+/

    build = buildRegex.match(content)[0]
    build
  else
    raise FileNotFound
  end
end

def populate_changelog
  metadata_dir = "./metadata/android/en-US/changelogs"

  version = fetch_version

  changelog = read_changelog(
    changelog_path: '../CHANGELOG.md',
    section_identifier: '[Android]'
  )

  destination = "#{metadata_dir}/#{version}.txt"

  File.open(destination, 'w') do |f|
    f << changelog
  end
end

  lane :beta do
    populate_changelog
    upload_to_play_store(track: 'beta', apk: '...', version_code: fetch_version)
  end
```

I use Flutter, so there is some opinionated things in there (regex from local.gradle), I'm not sure how different a normal Android project looks like so customize to your liking. The link I linked to has a more traditional approach, fetching directly from Google Play Store to get the correct version_code

Hope this helps

**Comment by pajapro** [comment]
> O don't really get how I can integrate this into my android fastlane deployment to set up automated changelog texts per build

@Psiiirus this plugin is platform independent, so the integration to Android project is the same as described in `README.md`. Please create an issue if you find _a specific problem_ with integration problem to Android.

**Comment by clragon** [comment]
very helpful, thanks @edisonywh

I have written my own version that extracts build numbers straight from the Changelog.md

```ruby

def fetch_versions
  path = "../CHANGELOG.md"
  content = File.read(path)
  regex = /## \[(.+\+\d+)\]/
  content.scan(regex).map(&:first)
end

def populate_changelog
  changelogs = "./metadata/android/en-US/changelogs"
  FileUtils.mkdir_p(changelogs)
  fetch_versions.each do |version|
    build_number = version.split("+")[1]
    File.open("#{changelogs}/#{build_number}.txt", 'w') do |f|
      f << read_changelog(section_identifier: "[#{version}]")
    end
  end
end
```
