### ISSUE TITLE
stamp_changelog action duplicates the last line in the [Unreleased] section

### ISSUE THREAD

**Issue by kdawgwilk** [pajapro/fastlane-plugin-changelog#47]
When you run the stamp_changelog action the last line of the [Unreleased] section gets duplicated into the newly stamped section.

Before
```
## [Unreleased]

### Added

- Some cool stuff
- Awesome stuff
- Amazing stuff!
```
After `stamp_changelog(section_identifier: 1.0.0)`
```
## [Unreleased]

## [1.0.0] - 2020-01-31

### Added

- Some cool stuff
- Awesome stuff
- Amazing stuff!
- Amazing stuff!
```

**Comment by wtimme** [comment]
I am also experiencing this (version `0.15.0`).

**Comment by pajapro** [comment]
Hi @kdawgwilk and @wtimme ,

I looked into this issue and extended the mock data for your scenario (https://github.com/pajapro/fastlane-plugin-changelog/commit/782f9ad9b9b3775b8bf60fec5f95b3f6fe5dd615 https://github.com/pajapro/fastlane-plugin-changelog/commit/416f322341f2a456e73ac1c64c531c8481dbce61). Unfortunately, I was not able to reproduce. If you look at the [mock file]((https://raw.githubusercontent.com/pajapro/fastlane-plugin-changelog/master/spec/fixtures/CHANGELOG_MOCK.md)) I use there is not space between `### Added` and the next line - could you try to remove the line break and see if it fixes the problem?

**Comment by wtimme** [comment]
Thanks for taking a look, @pajapro! I did the same, and even created a new test for this, but it ran successfully and without any problems.

With my own changelog, however, I still experience the issue. I've removed all but a few sections and added sample data:

```markdown
# Changelog
All notable changes to this project will be documented in this file.

## [Unreleased]
### Fixed
- My example bug fix

## [1.9.0 (1)] - 2020-02-15
### Added
- Some feature
```

I then ran the action with settings mentioned [above][1], which resulted in the following:

```markdown
# Changelog
All notable changes to this project will be documented in this file.

## [Unreleased]

## [2.0.0 (42)] - 2020-03-15
### Fixed
- My example bug fix

## [1.9.0 (1)] - 2020-02-15
### Added
- Some feature
- Some feature
```

As you can tell, the last line is duplicated. Are you able to reproduce this on your end?

[1]: https://github.com/pajapro/fastlane-plugin-changelog/issues/47#issuecomment-597917246

**Comment by pajapro** [comment]
> If I add an example tag to the changelog outlined above, I do no longer have duplicated lines. 

Super, glad to hear that you fixed it!

**Comment by mrtnrst** [comment]
@pajapro would it be possible to re-open this bug? If we use the param `git_tag` on the `stamp_changelog` action it still duplicates the last line. It feels as if this is not the expected outcome when the expected should be adding in the new ref link.

I see a few options here (mostly what is coming to my head right now):
1. It auto adds git tag links for any missing section headers (which feels to be the root of the problem)
2. If this is the first link added, set the compare to the `root` of the repo
3. Fail gracefully to not allow `git_tag` if there are versions in `CHANGELOG.md` without a git tag link.

Thoughts?
