### ISSUE TITLE
New action to combine changelogs

### ISSUE THREAD

**Issue by gdollardollar** [pajapro/fastlane-plugin-changelog#48]
Hi,

Not sure if that would interest you, but our workflow requires us to sometimes combine changelog that have a section prefix in common.

For example:
- we stamp the changelog for each dev build with the identifier `<version>-<build number>`
- when we release the full version we want the complete changelog for that version, which means combining the changelog for all sections that start  with `version`

We already have a custom action that does this, but felt like it would belong more with your plugin. If that interests you, I can make a pull request with our code?

Thanks!

**Comment by pajapro** [comment]
Hi @gdollardollar ,

that sounds like a very valid use-case our community could benefit from! 

Adding your custom action for such use-case to this plugin makes sense, so feel free to create PR  (please make sure to add unit tests) 💪.

Looking forward to your contribution
