### ISSUE TITLE
stamp_changelog: stamp_date does not support a user passed in date time string

### ISSUE THREAD

**Issue by donileo** [pajapro/fastlane-plugin-changelog#52]
For my changelogs I'm looking to include the time along with the date in the form of `2020-12-08T21:51Z`. Can support for passing a string for dates be added? 

So for example:

```
"stamp_date": "2020-12-08T21:51Z", <- takes false, true or a string..
```

**Comment by pajapro** [comment]
@donileo just released in https://github.com/pajapro/fastlane-plugin-changelog/releases/tag/v0.16.0
