### ISSUE TITLE
how to write message??

### ISSUE THREAD

**Issue by Odyflame** [pajapro/fastlane-plugin-changelog#55]
hi, i practice these plugin and write fastfile that

```
lane :release_testflight do
    
    changelog = read_changelog
  
    stamp_changelog(
        section_identifier: "#{get_version_number}", # Specify identifier to stamp the Unreleased section with
        git_tag: "Ver #{build_number}", # Specify reference to git tag associated with this section
        stamp_datetime_format: '%FT%TZ' # Specify strftime format string to use for the date in the stamped section (default `%FZ`)
    )
    
  end
```

like these. but when i run fastlane, i think there are some missunderstanding.

Added:
- New awesome feature

Changed:
- Onboarding flow 

Fixed:
- Fix Markdown links 

Removed:
- User tracking 

these template is not show in changeLog.md.

Should I write this in line with the template that I personally illustrated here on changelog.md?

what is real mean of read_changelog??
What's the difference between just handwriting on the git readme and this plugin?

**Comment by Odyflame** [comment]
just forget it. i solve :)

**Comment by dromerobarria** [comment]
Hi, I think Im in the same problem, I believe I can write in the changeLog with those commands can you explain it

**Comment by Odyflame** [comment]
Hi, @dromerobarria. there's not big issues. i'm sorry that i can't remember all that things cuz long time.. but i think it must have some tiny issue.

so i'm pretty sure you'll solve this problem.
