### ISSUE TITLE
stamp_changelog not stamp build date near a title 

### ISSUE THREAD

**Issue by alphatroya** [pajapro/fastlane-plugin-changelog#6]
'Keep a CHANGELOG' example uses the following pattern for titles : "## [0.3.0] - 2015-12-03", but the plugin does not paste build date after the bracket. I think it should do it by default. Alternative maybe there is an option for stamp_changelog method missed.

**Comment by pajapro** [comment]
Hi @alphatroya, thanks for your feedback. I have implemented this functionality in [v0.3.0](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/CHANGELOG.md#030---2015-08-09). 

`stamp_changelog` will now by default append current date in YYYY/MM/DD format to your section identifier. You can opt-out from this behaviour by `stamp_date: false`
