### ISSUE TITLE
The ability to skip stamping when [Unreleased] section is empty.

### ISSUE THREAD

**Issue by alphatroya** [pajapro/fastlane-plugin-changelog#7]
Now stamp_changelog generate new section even [Unreleased] section content is empty. Maybe there is one missing option that will skip command execution in that case.

**Comment by pajapro** [comment]
@alphatroya well, why would you want to stamp an empty `[Unreleased]` section? The point is to "stamp" whatever new features/fixes/deprecations are included in a build, I see no point in "stamping" an empty build, or?

**Comment by alphatroya** [comment]
I just want to prevent multiple empty fields appearing when the new build was triggered in CI and there is no content in Unreleased section.

<img width="334" alt="2016-08-11 15 34 21" src="https://cloud.githubusercontent.com/assets/4927633/17588671/39086628-5fd9-11e6-8c9a-f6b5a0a7c8ed.png">

**Comment by pajapro** [comment]
> I just want to prevent multiple empty fields appearing when the new build was triggered in CI and there is no content in Unreleased section.

Maybe I am missing something, but why do you trigger a new build from CI without any new changes in your source code?

**Comment by alphatroya** [comment]
There is always may be a situation when someone from team forgot to fill file, or manually trigger a build on CI. In this case, the changelog will be cluttered by unhelpful lines. I am talking about an optional parameter, this behaviour couldn't be a default.

**Comment by pajapro** [comment]
@alphatroya your feature request is now implemented and part of [0.4.0 release](https://github.com/pajapro/fastlane-plugin-changelog/blob/master/CHANGELOG.md#040---2015-08-27)
